### ISSUE TITLE
a few things

### ISSUE THREAD

**Issue by TylerS1066** [Team2168/2168_Vision_Example#2] opened 2015-02-12 23:13 UTC
For some reason the program doesn't recognize the following commands:
<code>cout</code>
<code>endl</code>
<code>setw</code>
<code>imshow</code>

And it has a error with vcap.open(videoStreamAddress) saying:
<code>
Invalid arguments '
Candidates are:
bool open(const ? &)
bool open(int, int, int, double)
'
</code>

Sorry if I'm missing something obvious

**Comment by NotInControl** [comment] 2015-02-13 22:04
Are you using your own program, or the one we provided?

If sounds like you are using your own project, in which case, you would need to add using namespace std; and using namespace cv; if you wanted to makes those calls. Or you can do std::cout, std::endl... etc. You can google more about namespaces if you are not familiar with what they are.

As for the invalid arguments, is videoStreamAddress a valid std::String type? post your code if fixing the namespace doesn't fix your issue with this.

**Comment by TylerS1066** [comment] 2015-02-13 22:33
I am using the program you provided, even the places the code says std::cout it still shows errors

videoStreamAddress is a valid std::String, it seems as if vcap.open() is looking for a bool

**Comment by NotInControl** [comment] 2015-02-14 06:31
Can you successfully create a new wpilib c++ project and build it without error?

**Comment by TylerS1066** [comment] 2015-02-15 01:13
Creating a new wpilib c++ project and building it works without errors

**Comment by TylerS1066** [comment] 2015-02-15 01:27
What i meant is that a basic wpilib project builds, not the vision code

**Comment by NotInControl** [comment] 2015-02-15 17:01
Please paste the full output of the console when trying to build the vision project so I can see exactly what errors you are having.

Also tell me what operating system you are using and what version of eclipse.

**Comment by TylerS1066** [comment] 2015-02-16 01:49
I am using Windows 8.1, eclipse version 4.4.1.20140925-1820

Console log:
[code]
19:48:55 **** Incremental Build of configuration Rio_Beagle for project 2168_Vision_Example ****
Info: Internal Builder is used for build
arm-frc-linux-gnueabi-g++ "-IC:\\Users\\Tyler\\workspace\\2168_Vision_Example\\_Includes\\OpenCV\\2.4.10" -O2 -g -Wall -c -fmessage-length=0 -fPIC -o "src\\main.o" "..\\src\\main.cpp" 
arm-frc-linux-gnueabi-g++ "-LC:\\Users\\Tyler\\workspace\\2168_Vision_Example\\_Libraries\\softFP\\lib_OpenCV" "-LC:\\Users\\Tyler\\workspace\\2168_Vision_Example\\_Libraries\\softFP\\lib_cpp" -Xlinker -rpath C:/Users/Tyler/workspace/2168_Vision_Example/_Libraries/softFP/lib_cpp -Xlinker -rpath C:/Users/Tyler/workspace/2168_Vision_Example/_Libraries/softFP/lib_OpenCV -o 2168_Vision_Example "src\\main.o" -lopencv_highgui -lopencv_core -lopencv_imgproc -lpthread -lrt 
c:/frc/bin/../lib/gcc/arm-frc-linux-gnueabi/4.9.1/../../../../arm-frc-linux-gnueabi/bin/ld.exe: warning: libstdc++.so.6, needed by C:\Users\Tyler\workspace\2168_Vision_Example\_Libraries\softFP\lib_OpenCV/libopencv_highgui.so, not found (try using -rpath or -rpath-link)
c:/frc/bin/../lib/gcc/arm-frc-linux-gnueabi/4.9.1/../../../../arm-frc-linux-gnueabi/bin/ld.exe: warning: libffi.so.6, needed by C:/Users/Tyler/workspace/2168_Vision_Example/_Libraries/softFP/lib_OpenCV/libgio-2.0.so.0, not found (try using -rpath or -rpath-link)

19:49:04 Build Finished (took 8s.843ms)
[/code]

**Comment by wdross** [comment] 2015-02-16 02:58
This is the same output that we see building this same project.

You can ignore the 2 Shared Object link errors, as those object files are on the roboRio and are loaded at run time.

Just transfer the binary file from Rio_Beagle folder to the roboRio and run it.

**Comment by NotInControl** [comment] 2015-02-16 09:45
I do not see any build errors in your log... it appears your build is successful. Look in the Rio_Beagle folder of the project (you may need to refresh your eclipse project explorer), you will see a file called 2168_Vision [arm]

That is the successful binary you compiled and can be transfered to the roborio or other arm7 target and executed. Please read the readme on the instructions of how to do that.

The warnings in your build log are known and can safely be ignored.

I am closing this issue as there appears to be no issue.

**Closed as completed** 2015-02-16 09:46 UTC

**Comment by TylerS1066** [comment] 2015-02-16 22:41
So all the errors that eclipse is giving me can be ignored?

**Comment by NotInControl** [comment] 2015-02-17 14:57
Tyler,

The output of eclipse you provided shows no errors at all. At this point, just going on the output of eclipse you posted, it appears you are successfully compiling our program. If you have a 2168_Vision file, in the Rio_Beagle folder, then you are done. 

I am not sure what errors you are talking about because your eclipse output doesn't show any errors. If you still feel you have errors, and are otherwise failing to compile, post a picture here of the errors you are talking about, or on cheifdelphi. A lot of teams are using this code as is, so it has been confirmed working by many others.
